### ISSUE TITLE
AttributeError: Can't pickle local object (only on Mac M1)

### ISSUE THREAD

**Issue by louis030195** [rom1504/clip-retrieval#142]
This error only occurs on Mac M1, and the same code works on Linux (gitpod.io), so it's not really an issue for me, but just in case to leave it as a placeholder if anyone has the same error.

https://gist.github.com/louis030195/416fea6224b86e8cb993cd9d5c22b894

(or if you suspect that it's unrelated to the environment?)

**Comment by hwazni** [comment]
Hi Louis, I am facing the same problem. Did you manage to solve it ?

**Comment by rom1504** [comment]
Solution is to make all functions first level

**Comment by hwazni** [comment]
once using the command 

`!clip-retrieval filter --query "cat" --output_folder "cat/" --indice_folder "indice_folder"`

I am getting the following error : 

```
Traceback (most recent call last):
  File "/usr/local/bin/clip-retrieval", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/clip_retrieval/cli.py", line 25, in main
    "parquet_to_arrow": parquet_to_arrow,
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/clip_retrieval/clip_filter.py", line 22, in clip_filter
    df = pd.concat(pd.read_parquet(parquet_file) for parquet_file in sorted(data_dir.glob("*.parquet")))
  File "/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```
