### ISSUE TITLE
Can't run inference with Open Clip models

### ISSUE THREAD

**Issue by BeardyBear** [rom1504/clip-retrieval#151]
Hi,

For some reason I can't run inference with Open Clip models.

This is what I'm getting when I try:

```
(venv_sauron) ubuntu@ip-***-**-*-***:~/code/sauron$ clip-retrieval inference --input_dataset data_output --output_folder embeddings_folder --clip_model "open_clip:ViT-B-32-quickgelu"
The number of samples has been estimated to be 1590
Traceback (most recent call last):
  File "/home/ubuntu/code/venv_sauron/bin/clip-retrieval", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/clip_retrieval/cli.py", line 16, in main
    fire.Fire(
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/clip_retrieval/clip_inference/main.py", line 144, in main
    distributor()
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/clip_retrieval/clip_inference/distributor.py", line 13, in __call__
    self.runner(i)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/clip_retrieval/clip_inference/runner.py", line 27, in __call__
    reader = self.reader_builder(sampler)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/clip_retrieval/clip_inference/main.py", line 71, in reader_builder
    _, preprocess = load_clip(clip_model=clip_model, use_jit=use_jit)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/clip_retrieval/clip_inference/load_clip.py", line 24, in load_clip
    return load_open_clip(clip_model, use_jit, device)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/clip_retrieval/clip_inference/load_clip.py", line 13, in load_open_clip
    model, _, preprocess = open_clip.create_model_and_transforms(
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/open_clip/factory.py", line 133, in create_model_and_transforms
    model = create_model(
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/open_clip/factory.py", line 119, in create_model
    model = torch.jit.script(model)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/torch/jit/_script.py", line 1265, in script
    return torch.jit._recursive.create_script_module(
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/torch/jit/_recursive.py", line 454, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/torch/jit/_recursive.py", line 516, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/torch/jit/_script.py", line 594, in _construct
    init_fn(script_module)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/torch/jit/_recursive.py", line 494, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/torch/jit/_recursive.py", line 516, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/torch/jit/_script.py", line 594, in _construct
    init_fn(script_module)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/torch/jit/_recursive.py", line 494, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/torch/jit/_recursive.py", line 520, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/torch/jit/_recursive.py", line 371, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/torch/jit/_recursive.py", line 841, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/torch/jit/_script.py", line 1315, in script
    ast = get_jit_def(obj, obj.__name__)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/torch/jit/frontend.py", line 264, in get_jit_def
    return build_def(parsed_def.ctx, fn_def, type_line, def_name, self_name=self_name, pdt_arg_types=pdt_arg_types)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/torch/jit/frontend.py", line 302, in build_def
    param_list = build_param_list(ctx, py_def.args, self_name, pdt_arg_types)
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/torch/jit/frontend.py", line 326, in build_param_list
    raise NotSupportedError(ctx_range, _vararg_kwarg_err)
torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:
  File "/home/ubuntu/code/venv_sauron/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 153
def checkpoint(function, *args, use_reentrant: bool = True, **kwargs):
                                                             ~~~~~~~ <--- HERE
    r"""Checkpoint a model or part of the model
```

I'm getting the same traceback with any of the Open Clip pretrained models that I've tried.

Can you please help me in overcoming this?

Thank you!

**Comment by rom1504** [comment]
hey,
ah wow I thought I had fixed that but forgot to release/commit it, will fix

**Comment by rom1504** [comment]
https://github.com/mlfoundations/open_clip/commit/a6396413b1423271db4cb1e6fd3392f53942198a is supposed to have fix it

can you check you indeed have open clip 1.2.1 ? (pip list)

trying in tests https://github.com/rom1504/clip-retrieval/pull/152

**Comment by BeardyBear** [comment]
@rom1504 turns out I had `1.1.1`, upgraded to `1.2.1` and it works!

Thank you very much.

I still have a question though..
When I run `open_clip.list_pretrained()` it returns pretrained models in tuples like that:

```
('ViT-B-32', 'laion2b_e16')
('ViT-B-32', 'laion400m_e31')
('ViT-B-32', 'laion400m_e32')
('ViT-B-32-quickgelu', 'laion400m_e31')
('ViT-B-32-quickgelu', 'laion400m_e32')
('ViT-B-16', 'laion400m_e31')
('ViT-B-16', 'laion400m_e32')
('ViT-B-16-plus-240', 'laion400m_e31')
('ViT-B-16-plus-240', 'laion400m_e32')
```

How do I run a specific model like `laion2b_e16` with `clip-retrieval`?

PS: unrelated, I've noticed that `clip-retrieval back` also exposes the frontend on its index endpoint, I suppose that's intended?

**Comment by rom1504** [comment]
> How do I run a specific model like laion2b_e16 with clip-retrieval?

good question, I think that's not supported as of now, would appreciate a pr !

> PS: unrelated, I've noticed that clip-retrieval back also exposes the frontend on its index endpoint, I suppose that's intended?

yes it's intended, is it causing you issues?

**Comment by BeardyBear** [comment]
> yes it's intended, is it causing you issues?

Not at all, asked out of curiousity,

> good question, I think that's not supported as of now, would appreciate a pr !

I will see what I can do :)

Anyways, thank you for this great library! Great write-up on Medium too.
