### ISSUE TITLE
clip-retrievel end2end throws "TypeError: sequence item 0: expected str instance, list found" on Windows

### ISSUE THREAD

**Issue by cherrerajobs** [rom1504/clip-retrieval#180]
Running Windows 10, 

 

> 0it [00:00, ?it/s]File sharded in 0 shards
Downloading starting now, check your bandwidth speed (with bwm-ng)your cpu (with htop), and your disk usage (with iotop)!
0it [00:00, ?it/s]
Traceback (most recent call last):                                                                                        
File "d:\miniconda3\envs\ldo\lib\runpy.py", line 194, in _run_module_as_main                                              return _run_code(code, main_globals, None,                                                                            
File "d:\miniconda3\envs\ldo\lib\runpy.py", line 87, in _run_code                                                         exec(code, run_globals)                                                                                               
File "D:\miniconda3\envs\ldo\Scripts\clip-retrieval.exe\__main__.py", line 7, in <module>                               File "d:\miniconda3\envs\ldo\lib\site-packages\clip_retrieval\cli.py", line 16, in main                                   fire.Fire(                                                                                                            
File "d:\miniconda3\envs\ldo\lib\site-packages\fire\core.py", line 141, in Fire                                           component_trace = _Fire(component, args, parsed_flag_args, context, name)                                             
File "d:\miniconda3\envs\ldo\lib\site-packages\fire\core.py", line 466, in _Fire                                          component, remaining_args = _CallAndUpdateTrace(                                                                      
File "d:\miniconda3\envs\ldo\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace                            component = fn(*varargs, **kwargs)                                                                                    
File "d:\miniconda3\envs\ldo\lib\site-packages\clip_retrieval\clip_end2end.py", line 37, in clip_end2end                  clip_inference(                                                                                                       
File "d:\miniconda3\envs\ldo\lib\site-packages\clip_retrieval\clip_inference\main.py", line 40, in main                   input_dataset = list(braceexpand(input_dataset))                                                                      
File "d:\miniconda3\envs\ldo\lib\site-packages\braceexpand\__init__.py", line 98, in <genexpr>                            return (_flatten(t, escape) for t in parse_pattern(pattern, escape))                                                  
File "d:\miniconda3\envs\ldo\lib\site-packages\braceexpand\__init__.py", line 216, in _flatten                            s = ''.join(l)                                                                                                      
TypeError: sequence item 0: expected str instance, list found

I think this has something to do with how parameters are handled on windows, I was getting a similar error before when using the example from https://github.com/rom1504/img2dataset/blob/main/dataset_examples/laion-aesthetic.md

> img2dataset --url_list laion2B-en-aesthetic --input_format "parquet"\
         --url_col "URL" --caption_col "TEXT" --output_format webdataset\
           --output_folder laion2B-en-aesthetic-data --processes_count 16 --thread_count 64 --image_size 384\
            --resize_only_if_bigger=True --resize_mode="keep_ratio" --skip_reencode=True \
             --save_additional_columns '["similarity","hash","punsafe","pwatermark","aesthetic"]' --enable_wandb True

 `--save_additional_columns` was not working and had to be removed

**Comment by lonleyodd** [comment]
excuse me, have you solved it?

**Comment by rom1504** [comment]
The solution is to use a better shell. Wsl for example

**Comment by JustinOstrowsky** [comment]
Getting the same error when running in collab

**Comment by mathyouf** [comment]
I am having the same issue running this on Ubuntu using ZSH.
<img width="691" alt="Screen Shot 2022-11-08 at 12 18 17 PM" src="https://user-images.githubusercontent.com/19615875/200666658-e7c6c30a-6231-4acf-8231-dc5fab1ad996.png">

**Comment by lizhiustc** [comment]
Same error on ubuntu
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/38285586/202167616-4e4ce5e1-6733-4b5c-ba92-c9afded9c504.png">

**Comment by m-bain** [comment]
Same here :(

**Comment by jefflab** [comment]
I get the same error on Mac using the [Clip end2end sample](https://github.com/rom1504/clip-retrieval#clip-end2end) from the README:

```
$ wget https://github.com/rom1504/img2dataset/raw/main/tests/test_files/test_1000.parquet
--2023-01-05 07:35:10--  https://github.com/rom1504/img2dataset/raw/main/tests/test_files/test_1000.parquet
Resolving github.com (github.com)... 192.30.255.112
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/rom1504/img2dataset/main/tests/test_files/test_1000.parquet [following]
--2023-01-05 07:35:11--  https://raw.githubusercontent.com/rom1504/img2dataset/main/tests/test_files/test_1000.parquet
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8000::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 131936 (129K) [application/octet-stream]
Saving to: ‘test_1000.parquet’

test_1000.parquet                                              100%[==================================================================================================================================================>] 128.84K  --.-KB/s    in 0.05s   

2023-01-05 07:35:11 (2.34 MB/s) - ‘test_1000.parquet’ saved [131936/131936]

b$ clip-retrieval end2end test_1000.parquet /tmp/my_output
/tmp/my_output
Starting the downloading of this file
Sharding file number 1 of 1 called /Users/jefflab/code/realtor-photo-copyright/deleteme/test_1000.parquet
0it [00:00, ?it/s]File sharded in 0 shards
Downloading starting now, check your bandwidth speed (with bwm-ng)your cpu (with htop), and your disk usage (with iotop)!
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/Users/jefflab/mambaforge/envs/clip-retrieval/bin/clip-retrieval", line 8, in <module>
    sys.exit(main())
  File "/Users/jefflab/mambaforge/envs/clip-retrieval/lib/python3.10/site-packages/clip_retrieval/cli.py", line 18, in main
    fire.Fire(
  File "/Users/jefflab/mambaforge/envs/clip-retrieval/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/jefflab/mambaforge/envs/clip-retrieval/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/jefflab/mambaforge/envs/clip-retrieval/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/jefflab/mambaforge/envs/clip-retrieval/lib/python3.10/site-packages/clip_retrieval/clip_end2end.py", line 37, in clip_end2end
    clip_inference(
  File "/Users/jefflab/mambaforge/envs/clip-retrieval/lib/python3.10/site-packages/clip_retrieval/clip_inference/main.py", line 105, in main
    expanded_dataset = list(braceexpand(input_dataset)) if input_format == "webdataset" else input_dataset
  File "/Users/jefflab/mambaforge/envs/clip-retrieval/lib/python3.10/site-packages/braceexpand/__init__.py", line 98, in <genexpr>
    return (_flatten(t, escape) for t in parse_pattern(pattern, escape))
  File "/Users/jefflab/mambaforge/envs/clip-retrieval/lib/python3.10/site-packages/braceexpand/__init__.py", line 216, in _flatten
    s = ''.join(l)
TypeError: sequence item 0: expected str instance, list found
```

**Comment by mathyouf** [comment]
For my exactly situation (not having captions) adding `--enable_text=False` solved my issue. Hope this helps someone, likely not the solution to everyone's problem, but perhaps related.

**Comment by xiuxiuxius** [comment]
I modified something like this

<img width="613" alt="image" src="https://github.com/rom1504/clip-retrieval/assets/89114157/24ca09e7-d7ea-4a0b-8aa5-b682d0caa1c9">

**Comment by rom1504** [comment]
can you open a PR @xiuxiuxius ?

**Comment by ShuxunoO** [comment]
I met the same case

`TypeError: sequence item 0: expected str instance, list found`

Can anyone help？

**Comment by xiuxiuxius** [comment]
> can you open a PR @xiuxiuxius ?

Never done it before, tried it, not sure if it's right
