### ISSUE TITLE
`NotImplementedError` 

### ISSUE THREAD

**Issue by thomastraum** [rom1504/clip-retrieval#208]
hi there. 

Thank you for this amazing project.
I am a trying to index a few images of my own and search them via the backend / frontend. 

I am on wls2 ubuntu and set up a miniconda environment and two gpu’s a 3090 and a 2070 Super. the nvidia drivers are installed for wsl2.

I created the dataset with 

```jsx
img2dataset --url_list='/home/thomas/code/meteor/clipping-things/public/urls.txt' --output_folder=dataset --thread_count=64 --image_size=256
```

then I am trying to run the interference but I always get this error. If I run the command a few more times it decides to use the cpu and works then

```jsx
(clip-retrieval-git) thomas@tm-9:~/code/clip-retrieval$ clip-retrieval inference --input_dataset "dataset/00000/" --output_folder embeddings
The number of samples has been estimated to be 5919
Starting the worker
dataset is 14
Starting work on task 0
/home/thomas/.local/lib/python3.8/site-packages/clip/clip.py:135: UserWarning: File /home/thomas/.cache/clip/ViT-B-32.pt is not a JIT archive. Loading as a state dict instead
  warnings.warn(f"File {model_path} is not a JIT archive. Loading as a state dict instead")
/home/thomas/.local/lib/python3.8/site-packages/torch/serialization.py:779: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
Traceback (most recent call last):
  File "/home/thomas/.local/bin/clip-retrieval", line 8, in <module>
    sys.exit(main())
  File "/home/thomas/.local/lib/python3.8/site-packages/clip_retrieval/cli.py", line 18, in main
    fire.Fire(
  File "/home/thomas/.local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/thomas/.local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/thomas/.local/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/thomas/.local/lib/python3.8/site-packages/clip_retrieval/clip_inference/main.py", line 154, in main
    distributor()
  File "/home/thomas/.local/lib/python3.8/site-packages/clip_retrieval/clip_inference/distributor.py", line 17, in __call__
    worker(
  File "/home/thomas/.local/lib/python3.8/site-packages/clip_retrieval/clip_inference/worker.py", line 122, in worker
    runner(task)
  File "/home/thomas/.local/lib/python3.8/site-packages/clip_retrieval/clip_inference/runner.py", line 29, in __call__
    reader = self.reader_builder(sampler)
  File "/home/thomas/.local/lib/python3.8/site-packages/clip_retrieval/clip_inference/worker.py", line 52, in reader_builder
    _, preprocess = load_clip(
  File "/home/thomas/.local/lib/python3.8/site-packages/clip_retrieval/load_clip.py", line 73, in load_clip
    model, preprocess = load_clip_without_warmup(clip_model, use_jit, device, clip_cache_path)
  File "/home/thomas/.local/lib/python3.8/site-packages/clip_retrieval/load_clip.py", line 64, in load_clip_without_warmup
    model, preprocess = clip.load(clip_model, device=device, jit=use_jit, download_root=clip_cache_path)
  File "/home/thomas/.local/lib/python3.8/site-packages/clip/clip.py", line 140, in load
    model = build_model(state_dict or model.state_dict()).to(device)
  File "/home/thomas/.local/lib/python3.8/site-packages/clip/model.py", line 396, in build_model
    vit = "visual.proj" in state_dict
  File "/home/thomas/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 844, in __contains__
    return self.forward_magic_method("__contains__", key)
  File "/home/thomas/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 831, in forward_magic_method
    raise NotImplementedError()
NotImplementedError
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
```

If I run it on the cpu I later get this error when trying to run it

```jsx
(base) thomas@tm-9:~/code/clip-retrieval-pip$ clip-retrieval back --port 1234 --indices-paths indices_paths.json
starting boot of clip back
/home/thomas/.local/lib/python3.8/site-packages/clip/clip.py:135: UserWarning: File /home/thomas/.cache/clip/ViT-B-32.pt is not a JIT archive. Loading as a state dict instead
  warnings.warn(f"File {model_path} is not a JIT archive. Loading as a state dict instead")
/home/thomas/.local/lib/python3.8/site-packages/torch/serialization.py:779: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
Traceback (most recent call last):
  File "/home/thomas/.local/bin/clip-retrieval", line 8, in <module>
    sys.exit(main())
  File "/home/thomas/.local/lib/python3.8/site-packages/clip_retrieval/cli.py", line 18, in main
    fire.Fire(
  File "/home/thomas/.local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/thomas/.local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/thomas/.local/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/thomas/.local/lib/python3.8/site-packages/clip_retrieval/clip_back.py", line 965, in clip_back
    clip_resources = load_clip_indices(
  File "/home/thomas/.local/lib/python3.8/site-packages/clip_retrieval/clip_back.py", line 938, in load_clip_indices
    clip_resources[name] = load_clip_index(clip_options)
  File "/home/thomas/.local/lib/python3.8/site-packages/clip_retrieval/clip_back.py", line 860, in load_clip_index
    model, preprocess = load_clip(clip_options.clip_model, use_jit=clip_options.use_jit, device=device)
  File "/home/thomas/.local/lib/python3.8/site-packages/clip_retrieval/load_clip.py", line 73, in load_clip
    model, preprocess = load_clip_without_warmup(clip_model, use_jit, device, clip_cache_path)
  File "/home/thomas/.local/lib/python3.8/site-packages/clip_retrieval/load_clip.py", line 64, in load_clip_without_warmup
    model, preprocess = clip.load(clip_model, device=device, jit=use_jit, download_root=clip_cache_path)
  File "/home/thomas/.local/lib/python3.8/site-packages/clip/clip.py", line 140, in load
    model = build_model(state_dict or model.state_dict()).to(device)
  File "/home/thomas/.local/lib/python3.8/site-packages/clip/model.py", line 396, in build_model
    vit = "visual.proj" in state_dict
  File "/home/thomas/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 844, in __contains__
    return self.forward_magic_method("__contains__", key)
  File "/home/thomas/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 831, in forward_magic_method
    raise NotImplementedError()
NotImplementedError
```

**Comment by rom1504** [comment]
can you try to --use_jit=False ?

**Comment by thomastraum** [comment]
@rom1504 thanks so much this worked at least for the backend. I am sorry that I missed this in the options on the readme. 

this is so impressive.... the results are crazy good
