### ISSUE TITLE
AttributeError: Can't pickle local object 'get_image_dataset.<locals>.ImageDataset'

### ISSUE THREAD

**Issue by zhenzi0322** [rom1504/clip-retrieval#220]
```bash
clip-retrieval inference --input_dataset image_folder --output_folder embeddings_folder --num_prepro_workers 1
```

```
   reduction.dump(process_obj, to_child)
  File "D:\packages\python\python395\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_image_dataset.<locals>.ImageDataset'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\packages\python\python395\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\packages\python\python395\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Comment by grexzen** [comment]
Fixed by changing num prepro workers to 0 to stop multiprocessing that causes the error.
