### ISSUE TITLE
Is there a way to extend the clip-back server

### ISSUE THREAD

**Issue by Sadeeed** [rom1504/clip-retrieval#287]
I am implementing this for an app and I'd like to have more info from the images is there a way for me to extend the functionality without modifying clip-retrieval itself?

**Comment by rom1504** [comment]
All metadata columns are provided to the front end, so if you modify the
front end to display what you want it'll work

**Comment by Sadeeed** [comment]
I am only using the backend API's with a custom dataset created with img2dataset with embeddings and indices created with clip-retrieval the issue is that when I create the dataset from my db it loses some information like the seed, image_url etc. I'd like to keep that info in the generated dataset assuming it can fetched later on with either the knn-service endpoint or the metadata endpoint.

is there a way to do this?

**Comment by rom1504** [comment]
Yes --save_additional_columns in img2dataset and --save_metadata in clip
back inference

**Comment by Sadeeed** [comment]
okay thankyou

**Comment by Sadeeed** [comment]
I am using this command to generate a dataset with additional columns
```
img2dataset "csv/anything-v3.csv" --input_format="csv" --url_col "image_url" --caption_col "prompt" --save_additional_columns=["seed", "model_version"] --output_folder="test" --resize_mode="no" --output_format="files" 
```
but it throws this error
```
Traceback (most recent call last):
  File "/Users/icesoup/Documents/Source/Python/Samaritan/prompt-search/venv/bin/img2dataset", line 8, in <module>
    sys.exit(main())
  File "/Users/icesoup/Documents/Source/Python/Samaritan/prompt-search/venv/lib/python3.10/site-packages/img2dataset/main.py", line 262, in main
    fire.Fire(download)
  File "/Users/icesoup/Documents/Source/Python/Samaritan/prompt-search/venv/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/icesoup/Documents/Source/Python/Samaritan/prompt-search/venv/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/icesoup/Documents/Source/Python/Samaritan/prompt-search/venv/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/icesoup/Documents/Source/Python/Samaritan/prompt-search/venv/lib/python3.10/site-packages/img2dataset/main.py", line 175, in download
    reader = Reader(
  File "/Users/icesoup/Documents/Source/Python/Samaritan/prompt-search/venv/lib/python3.10/site-packages/img2dataset/reader.py", line 67, in __init__
    self.column_list = self.column_list + ["caption"]
TypeError: can only concatenate str (not "list") to str
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/icesoup/.pyenv/versions/3.10.12/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/icesoup/.pyenv/versions/3.10.12/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/Users/icesoup/.pyenv/versions/3.10.12/lib/python3.10/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
Segmentation fault: 11

```

**Comment by rom1504** [comment]
`--save_additional_columns=["seed", "model_version"]` should be `--save_additional_columns='["seed", "model_version"]'` due to how bash works

**Comment by Sadeeed** [comment]
sorry to keep annoying you but I cant get save_metadata working and I couldn't find anything about it in the docs

im using this command
`clip-retrieval inference --input_dataset test --save_metadata='true' --output_folder test_embeddings`
 I have also tried `--save_metadata='yes'` `--save_metadata true` but it throws the same error
 `ERROR: Could not consume arg: --save_metadata=yes`

**Comment by rom1504** [comment]
https://github.com/rom1504/clip-retrieval#api

enable_metadata

**Comment by Sadeeed** [comment]
thank you once again for the help 🙇
