### ISSUE TITLE
Problems installing backend ("index_combiner" not found)

### ISSUE THREAD

**Issue by FlimFlamm** [rom1504/clip-retrieval#300]
I'm trying to download and install the "clip-back with an H/14 index of Laion5B", and am having a difficult time.

I managed to download the index parquet files, but I'm stuck trying to combine them:
`
    clip-retrieval index_combiner --input_folder "index-parts" --output_folder "combined-indices"
`
"index_combiner" is not being recognized as a command, which leads me to wonder whether something is corrupt regarding my python environment, or whether changes to clip-retrieval are simply not yet reflected in the clip-back H/14 guide.

Any advice or directions on how I can progress?

EDIT: installing from source fixes this issue, but leads to a new one (see below):

**Comment by FlimFlamm** [comment]
After installing from source, this is the closest I can get to building the combined index:

`(clipmancer) C:\Users\chris\Documents\cadmancer\local_clip>clip-retrieval index_combiner --input_folder "index-parts" --output_folder "combined-indices"
Traceback (most recent call last):
  File "C:\Users\chris\miniconda3\envs\clipmancer\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chris\miniconda3\envs\clipmancer\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\chris\miniconda3\envs\clipmancer\Scripts\clip-retrieval.exe\__main__.py", line 7, in <module>
  File "C:\Users\chris\miniconda3\envs\clipmancer\lib\site-packages\clip_retrieval\cli.py", line 18, in main
    fire.Fire(
  File "C:\Users\chris\miniconda3\envs\clipmancer\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\chris\miniconda3\envs\clipmancer\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\chris\miniconda3\envs\clipmancer\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\chris\miniconda3\envs\clipmancer\lib\site-packages\clip_retrieval\clip_back_prepro\index_combiner.py", line 14, in index_combiner
    empty_index = faiss.read_index(block_fnames[0], faiss.IO_FLAG_MMAP)
  File "C:\Users\chris\miniconda3\envs\clipmancer\lib\site-packages\faiss\swigfaiss.py", line 9795, in read_index
    return _swigfaiss.read_index(*args)
RuntimeError: Error in struct faiss::InvertedListsIOHook *__cdecl faiss::InvertedListsIOHook::lookup(int) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\invlists\InvertedListsIOHook.cpp:63: read_InvertedLists: could not load ArrayInvertedLists as 646f6c69 ("ilod")`

I'm on Windows 10, if that matters...

**Comment by FlimFlamm** [comment]
Just to add some details to my install process and where the problems are ocuring:

From the h/14 guide, `pip install huggingface_hub clip-retrieval` results in torch 2.0.1 being installed, which appears to be incompatible with the git's `requirements.txt` (perhaps requirements is simply outdated?).

Forcing a compatible torch version at this point leads to the error linked in the previous post after installing from source, otherwise `index_compiler` will not be included. I also grabbed the index_compiler script directly.

Examining things more deeply, the faiss operation in the index_combiner is the root of my problem, which seems to be due to the fact that I have 80 `.parquet` files instead of 80 .index files (the faiss format afaik). Is this by design or must I have erred? (I used the bash code provided by the instructions). Is there a way to convert these to the format I require?

**Comment by FlimFlamm** [comment]
Having looked more deeply into this, it's possible that windows OS and on-disk operations is the root cause of the issue. see: https://github.com/facebookresearch/faiss/issues/2106 

If this is the case, are there any alternatives for combining the index files that won't necessitate switching to Linux?

**Comment by FlimFlamm** [comment]
Closing this...

Switching to Linux did solve this issue; apparently it just cant happen on windows.
