### ISSUE TITLE
server question?

### ISSUE THREAD

**Issue by xinli2008** [rom1504/clip-retrieval#306]
hello, i have installed the clip-retrieval package and try the demo code as follows:

`from clip_retrieval.clip_client import ClipClient, Modality

client = ClipClient(url="https://knn.laion.ai/knn-service", indice_name="laion5B-L-14")

results = client.query(text="an image of a cat")

results[0]
`
but the error happens:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/clip_retrieval/clip_client.py", line 84, in query
    return self.__search_knn_api__(text=text)
  File "/usr/local/lib/python3.8/dist-packages/clip_retrieval/clip_client.py", line 131, in __search_knn_api__
    return requests.post(
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>> results = client.query(text="an image of a cat")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/clip_retrieval/clip_client.py", line 84, in query
    return self.__search_knn_api__(text=text)
  File "/usr/local/lib/python3.8/dist-packages/clip_retrieval/clip_client.py", line 131, in __search_knn_api__
    return requests.post(
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

It seems that something happened with the server? @

**Comment by Sandeep-Narahari** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/diffusers/examples/custom_diffusion/retrieve.py", line 92, in <module>
    retrieve(args.class_prompt, args.class_data_dir, args.num_class_images)
  File "/content/diffusers/examples/custom_diffusion/retrieve.py", line 37, in retrieve
    class_images = client.query(text=class_prompt)
  File "/usr/local/lib/python3.10/dist-packages/clip_retrieval/clip_client.py", line 84, in query
    return self.__search_knn_api__(text=text)
  File "/usr/local/lib/python3.10/dist-packages/clip_retrieval/clip_client.py", line 152, in __search_knn_api__
    ).json()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I am facing the same issue , any on here to help , any update on this Thank you

**Comment by rom1504** [comment]
Automated throttling happens when too many requests are being queued.

Try to slow down your request rate and retry

What is your use case ?

**Comment by Sandeep-Narahari** [comment]
Before  training the custom diffusion model there is a step which to(collect 200 real images using clip-retrieval which are combined with the target images in the training dataset as a regularization. This prevents overfitting to the the given target image
)
https://github.com/huggingface/diffusers/blob/main/examples/custom_diffusion/retrieve.py
https://github.com/huggingface/diffusers/tree/main/examples/custom_diffusion

**Comment by Sandeep-Narahari** [comment]
I will be using this for production purpose , so how can I solve this issue @rom1504  , Thanks

**Comment by rom1504** [comment]
If you want to use it for production I advise you host the index yourself.
See the guide for how to do it in the readme

**Comment by daeunni** [comment]
@Sandeep-Narahari  Hi, I have a same issue. Did you address it?

**Comment by rom1504** [comment]
#324
