### ISSUE TITLE
issue with inference

### ISSUE THREAD

**Issue by wisebreadloaf** [rom1504/clip-retrieval#345]
~/clip-retriever  master [!?] +93 -97  98% ............................................................................................................................via 🐍 v3.11.6 (env) 
❯ clip-retrieval inference --input_dataset ./source_images/ --output_folder ./output_folder/
The number of samples has been estimated to be 22
Starting the worker
dataset is 16
Starting work on task 0
warming up with batch size 256 on cuda
done warming up in 24.880407333374023s
Traceback (most recent call last):
  File "/home/bored/clip-retriever/env/bin/clip-retrieval", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/clip_retrieval/cli.py", line 18, in main
    fire.Fire(
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/clip_retrieval/clip_inference/main.py", line 154, in main
    distributor()
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/clip_retrieval/clip_inference/distributor.py", line 17, in __call__
    worker(
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/clip_retrieval/clip_inference/worker.py", line 127, in worker
    runner(task)
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/clip_retrieval/clip_inference/runner.py", line 39, in __call__
    batch = iterator.__next__()
            ^^^^^^^^^^^^^^^^^^^
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/clip_retrieval/clip_inference/reader.py", line 225, in __iter__
    for batch in self.dataloader:
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/bored/clip-retriever/env/lib/python3.11/site-packages/clip_retrieval/clip_inference/reader.py", line 99, in __getitem__
    image_file = self.image_files[key]
                 ~~~~~~~~~~~~~~~~^^^^^
KeyError: 'image1.txt'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/synchronize.py", line 115, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory

**Comment by hknguyen20** [comment]
Encountering same problem with Python3.10 on Macbook M1 running with cpu.

**Comment by rom1504** [comment]
Is source folder empty ? Did you try with an absolute path

**Comment by rom1504** [comment]
You may need to --enable_text False if you don't have any captions

**Comment by hknguyen20** [comment]
Thanks for answering. The source folder is not empty and I think it did read the folder as the output printed "The number of samples has been estimated to be ...". There is no captions but --enable_text False still gives the same error.

**Comment by rom1504** [comment]
Did you try with an absolute path ?

 Can you share a ls of the content?

What operating system are you using?

**Comment by rom1504** [comment]
Looks like the error is `AttributeError: Can't pickle local object
'get_image_dataset.<locals>.ImageDataset'
Traceback (most recent call last):`

Something different about how macos handle things

**Comment by hknguyen20** [comment]
I see. It's same issue as #142

**Comment by rom1504** [comment]
Can you try making https://github.com/rom1504/clip-retrieval/blob/ee0931f89c69cf2e39b5187d50a40873b7999d2b/clip_retrieval/clip_inference/reader.py#L59 top level and rerun ?

**Comment by rohun-tripathi** [comment]
I see a similar error when trying to use this - 

KeyError: '00000/000000000.txt'

Happens after I captions with the same name as a the image next to the image. How do the captions have to be placed?

**Comment by rom1504** [comment]
@rohun-tripathi can you provide more information? Command, environment,...

This is not expected

**Comment by ShuxunoO** [comment]
If you met the same errors，trying to refer to: https://github.com/rom1504/clip-retrieval/issues/352
