### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by daeunni** [rom1504/clip-retrieval#346]
Hi, thanks for your amazing library! 
I am wondering about the issue related to JSONDecodeError. 
I was trying to run the code below. My version is 2.44.0 (pip). 
`client = ClipClient(url="https://knn.laion.ai/knn-service", indice_name="laion5B-L-14", num_images=num_images,  aesthetic_weight=0.1)`

However, I encountered these errors. 
```
Traceback (most recent call last):
  File "src/retrieve.py", line 97, in <module>
    retrieve(args.target_name, args.outpath, args.num_class_images)
  File "src/retrieve.py", line 33, in retrieve
    results = client.query(text=target_name)   # similar to target 
  File "/d1/daeun/anaconda3/env/diff/lib/python3.8/site-packages/clip_retrieval/clip_client.py", line 84, in query
    return self.__search_knn_api__(text=text)
  File "/d1/daeun/anaconda3/env/diff/lib/python3.8/site-packages/clip_retrieval/clip_client.py", line 131, in __search_knn_api__
    return requests.post(
  File "/d1/daeun/anaconda3/env/diff/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

I already checked the previous issues, but is there any solution to solve it?
I was about to run [CustomDiffusion](https://github.com/adobe-research/custom-diffusion/issues/35)

**Comment by rom1504** [comment]
#324
